eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: false
    hostname: localhost
    lease-renewal-interval-in-seconds: 15
    lease-expiration-duration-in-seconds: 15
server:
  port: 8762
spring:
  application:
    name: zuul-server
management:
  endpoints:
    web:
      exposure:
        include: "*"
zuul:
  routes:
    spring-cloud-eureka-client:
      path: /test/**
      serviceId: spring-cloud-eureka-client